default: &default
    adapter: postgresql
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000

development:
    <<: *default
    database: prueba_db # El nombre que le quiera dar a la BD del proyecto
    username: maikol  # El usuario con el que se halla configurado postgres
    password:          # Si le dio un password a la configuración del usuario en postgres coloca